name: Run Python Script Every 5 Seconds

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Python script in a loop
        run: |
          for i in {1..12}; do  # Runs 12 times (every 5 seconds for 1 min)
            python n8ntest.py  # Change to your script name

            sleep 5  # Wait for 5 seconds before running again
          done

