name: Run Python Script Every 1 Hour 10 Minutes

on:
  schedule:
    - cron: "10 */1 * * *"  # Runs every 1 hour 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip packages
          key: python-dependencies-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-dependencies-${{ runner.os }}-

      - name: Install dependencies (only if not cached)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Python script in a loop
        run: |
          for i in {1..12}; do  # Runs 12 times (every 5 seconds for 1 minute)
            python scheduleBRCP.py  # Change to your script name
            sleep 5  # Wait for 5 seconds before running again
          done
